# Generated by Django 2.0.1 on 2018-01-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0003_ticker_coinmarketid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='coinMarketId',
        ),
    ]
