# Generated by Django 2.0.1 on 2018-01-30 16:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0005_tickerhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickerhistory',
            options={'verbose_name_plural': 'ticker histories'},
        ),
        migrations.AlterField(
            model_name='ticker',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='lastAnalyzed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
