# Generated by Django 2.0.1 on 2018-02-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0006_auto_20180130_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='dayVolumeBtc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='dayVolumeBtc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
