# Generated by Django 2.0.1 on 2018-02-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0007_auto_20180202_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='marketCapBtc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='marketCapBtc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
