# Generated by Django 2.0.1 on 2018-02-05 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0008_auto_20180202_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='markedCapUsd',
            new_name='marketCapUsd',
        ),
        migrations.RenameField(
            model_name='tickerhistory',
            old_name='markedCapUsd',
            new_name='marketCapUsd',
        ),
    ]
