# Generated by Django 2.0.1 on 2018-02-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0010_auto_20180208_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='btcPercentChange1h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='btcPercentChange24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ticker',
            name='btcPercentChange7d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='btcPercentChange1h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='btcPercentChange24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='btcPercentChange7d',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
