# Generated by Django 2.0.1 on 2018-02-28 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickers', '0013_auto_20180221_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='btcLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickers.Ticker'),
        ),
        migrations.AddField(
            model_name='tickerhistory',
            name='btcLink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickers.TickerHistory'),
        ),
    ]
